#!/bin/sh
#
# This file is a component of the i-doit framework
# http://www.i-doit.org
#
# Licence: http://www.gnu.org/licenses/agpl-3.0.html GNU AGPLv3
# Author:  dennis stuecken <dstuecken@synetics.de>
# Date:    28.01.2008

./controller -v -m import $@
