#!/bin/sh
#
# This file is a component of the i-doit framework
# http://www.i-doit.org
#
# Licence:   http://www.gnu.org/licenses/agpl-3.0.html GNU AGPLv3
# Author:    dennis stuecken <dstuecken@synetics.de>
# Copyright: synetics GmbH
# Date:      28.01.2008

IDOIT_PATH=`pwd`
PHP5=$(which php5)

if [ "$PHP5" = "" ]; then
  PHP5=$(which php)
fi

### SCRIPT
cd $IDOIT_PATH
$PHP5 controller.php -v -m tenants $1 $2 $3
