#!/bin/sh
#
# This file is a component of the i-doit framework
# http://www.i-doit.org
#
# Make sure your php extension "curl" is enabled/installed in order to
# check for i-doit updates.
#
# For update checking behind a proxy server, configure your proxy in
# src/config.inc.php.
#
# Licence: http://www.gnu.org/licenses/agpl-3.0.html GNU AGPLv3
# Author:  dennis stuecken <dstuecken@synetics.de>
# Date:    20.08.2009

./controller -v -m updatecheck $@
